# Generated by Django 2.1.5 on 2020-07-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('year', models.DateTimeField()),
                ('actores', models.TextField()),
                ('duracion', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
    ]
