# Generated by Django 2.1.5 on 2020-08-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
