# Generated by Django 2.1.5 on 2020-08-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='mod',
            field=models.TextField(null=True),
        ),
    ]
