# Generated by Django 2.1.5 on 2020-08-14 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_pelicula_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='year',
        ),
    ]
