# Generated by Django 2.1.5 on 2020-08-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_remove_pelicula_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='text',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
