# Generated by Django 2.1.5 on 2020-08-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_auto_20200814_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.DateField(),
        ),
    ]
